
enum class Animations {
    COLOR1,
    COLOR2,
    COLOR3,
    COLOR4,
    ALTERNATE,
    MULTIPIXELRUN,
    MULTIPIXELRUNTOCOLOR,
    PIXELRUN,
    PIXELMARATHON,
    SMOOTHCHASE,
    SPARKLE,
    SPARKLECC,
    SPARKLETOCOLOR,
    STACK,
    STACKOVERFLOW,
    WIPE
}