name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
#      - name: Cache Gradle packages
#        uses: actions/cache@v2.1.4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
      - name: Create test classes for testing
        run: ./gradlew jvmTestClasses

#      - name: Test
#        run: ./gradlew jvmTest
      - name: Test
        run: ./gradlew koverXmlReport
      - name: Upload coverage
        uses: codecov/codecov-action@v1.3.1

#      - name: Cleanup Gradle Cache
#        run: |
#          rm -f ~/.gradle/caches/modules-2/modules-2.lock
#          rm -f ~/.gradle/caches/modules-2/gc.properties
