name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"
      - name: Create test classes for testing
        run: ./gradlew jvmTestClasses

      - name: Test
        run: ./gradlew koverXmlReport
      - name: Upload coverage
        uses: codecov/codecov-action@v4
